name: Lint Markdown Data

on:
  workflow_dispatch:
  pull_request:

jobs:

  pr-title-validator:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: .github/pr-title-checker-config.json
          pass_on_octokit_error: false

  md-linter:
    name: Lint markdown
    runs-on: ubuntu-latest
    needs: pr-title-validator
    steps:
      - uses: actions/checkout@v3
      - name: Markdown Lint
      - uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .markdownlint.json